steps:
  - name: "gcr.io/kaniko-project/executor:v1.6.0"
    args: [
          "--cache=true",
          "--destination=gcr.io/$PROJECT_ID/event-processor-q422:latest",
          "--dockerfile", "processor/Dockerfile",
          "--context", "dir://processor"
    ]
    waitFor: ["-"]
  - name: "gcr.io/kaniko-project/executor:v1.6.0"
    args: [
          "--cache=true",
          "--destination=gcr.io/$PROJECT_ID/event-notifier-q422:latest",
          "--dockerfile", "notifier/Dockerfile",
          "--context", "dir://notifier"
    ]
    waitFor: ["-"]
  - name: "gcr.io/kaniko-project/executor:v1.6.0"
    args: [
          "--cache=true",
          "--destination=gcr.io/$PROJECT_ID/request-bin-q422:latest",
          "--dockerfile", "request_bin/Dockerfile",
          "--context", "dir://request_bin"
    ]
    waitFor: ["-"]
  - name: "gcr.io/kaniko-project/executor:v1.6.0"
    args: [
          "--cache=true",
          "--destination=gcr.io/$PROJECT_ID/telegram-service-q422:latest",
          "--dockerfile", "telegram/Dockerfile",
          "--context", "dir://telegram"
    ]
    waitFor: ["-"]
options:
    machineType: 'N1_HIGHCPU_32'
timeout: 900s