replicaCount: 1
commitsh: "latest"

beanstalkd:
  image:
    repository: schickling/beanstalkd
    pullPolicy: IfNotPresent
    tag: "latest"
  port: 11300
  maxJobSize: 65535
  binlogSize: "20Mi"
  replicaCount: 1
  name: beanstalkd
  service:
    type: ClusterIP
    fqdn: rc1staging-governance-notifications-beanstalkd.event-notifications.svc.cluster.local

processor:
  name: event-processor
  image:
    repository: gcr.io/celo-testnet-production/event-processor-q422
    pullPolicy: Always
    tag: "latest"
  readDelay: 1 
  replicaCount: 1

notifier:
  name: event-notifier
  image:
    repository: gcr.io/celo-testnet-production/event-notifier-q422
    pullPolicy: Always
    tag: "latest"
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 80

monitor:
  name: beanstalkd-monitor
  image:
    repository: agaveapi/beanstalkd-console
    pullPolicy: Always
    tag: "latest"
  replicaCount: 1

requestbin:
  name: request-bin
  image:
    repository: gcr.io/celo-testnet-production/request-bin-q422
    pullPolicy: Always
    tag: "latest"
  replicaCount: 1
  service:
    type: ClusterIP
    fqdn: rc1staging-governance-notifications-request-bin.event-notifications.svc.cluster.local

telegram:
  name: telegram
  image:
    repository: gcr.io/celo-testnet-production/telegram-q422
    pullPolicy: Always
    tag: "latest"
  replicaCount: 1
  subscriptionTube: "subscriptions"
  pollTimeSeconds: 2
  metrics:
    enabled: true
    path: /metrics
    port: 4000
  service:
    type: ClusterIP
    fqdn: rc1staging-governance-notifications-telegram.event-notifications.svc.cluster.local
  resources:
    memory: 1000Mi
    cpu: 2

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000


ingress:
  enabled: false
  className: ""
  annotations: 
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: search.celo-networks-dev.org
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
    - secretName: search-web-tls
      hosts:
        - search.celo-networks-dev.org

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

metrics:
  enabled: true
  image:
    repository: dtannock/beanstalkd-exporter
    pullPolicy: IfNotPresent
    tag: "0.1.1"
  path: /metrics
  port: 11301

nodeSelector: {}

tolerations: []

affinity: {}