apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-beanstalkd
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type}}
  ports:
    - port: {{ .Values.beanstalkd.port }}
      targetPort: {{ .Values.beanstalkd.port }}
      protocol: TCP
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
    component: beanstalkd
{{- if .Values.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-metrics
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type}}
  ports:
  - name: metrics
    port: {{ .Values.metrics.port }}
    targetPort: metrics
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
    component: beanstalkd
{{- end }}
