apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-request-bin
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
    component: request-bin
