apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}-{{ .Values.telegram.name}}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.telegram.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.telegram.metrics.enabled }}
        prometheus.io/scrape: 'true'
        prometheus.io/path: {{ .Values.telegram.metrics.path | quote}}
        prometheus.io/port: {{ .Values.telegram.metrics.port | quote}}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
        component: {{ .Values.telegram.name}}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.telegram.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.telegram.image.repository }}:{{ .Values.telegram.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.telegram.image.pullPolicy }}
          resources:
            requests:
            {{- toYaml .Values.telegram.resources | nindent 14 }}
          env:
          - name: BEANSTALKD_HOST
            value: "{{ .Values.beanstalkd.service.fqdn }}"
          - name: BEANSTALKD_PORT
            value: "{{ .Values.beanstalkd.port }}"
          - name: BEANSTALKD_TUBE
            value: "{{ .Values.telegram.subscriptionTube }}"
          - name: BOT_TIME_POLL_SECONDS
            value: "{{ .Values.telegram.pollTimeSeconds }}"
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: telegram
                key: phoenix-secret-key-base
          - name: TELEGRAM_BOT_SECRET
            valueFrom:
              secretKeyRef:
                name: telegram
                key: api-token

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
