apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-{{ .Values.telegram.name }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4000
      protocol: TCP
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
    component: {{ .Values.telegram.name }}