send_cusd_event:
	curl -v -X POST -H 'Content-Type: application/json' localhost:4000/api/receive --data-binary @test/events/cusd_event
send_governance_event:
	curl -v -X POST -H 'Content-Type: application/json' localhost:4000/api/receive --data-binary @test/events/governance
	
